#!/bin/bash

#unblock wifi
#needed after buster 20200205
rfkill unblock all > /dev/null 2>&1

#update packages
apt-get update

#install hostapd, dnsmasq
apt-get install -y hostapd
apt-get install -y dnsmasq

#remove hostapd mask
systemctl unmask hostapd

#stop both services
systemctl disable hostapd
systemctl disable dnsmasq

wifisetup() {
echo;echo;echo
echo "This password will be used to connect to the pi"
echo "when the pi is in hotspot mode"
#credit next line to Ray, N3HYM
echo "Hotspot name"
read -p "Enter hotspot name to use " ssid
echo "Interface name"
read -p "Enter the interface to be used " interface
echo "Password should be between 8-63 characters"
read -p "Enter password to use with new hotspot " wifipasswd
COUNT=${#wifipasswd}
if [ $COUNT -lt 8 ]
then
echo "Password must be at least 8 characters long"
sleep 2
wifisetup
fi
echo;echo
echo "You entered $wifipasswd"
read -p "Is this correct? y/n " wifians
if [ $wifians == "y" ] || [ $wifians == "Y" ]
then
echo
else
wifisetup
fi
}

wifisetup

#add needed info to hostapd.conf
echo "#2.4GHz setup wifi 80211 b,g,n" > /etc/hostapd/hostapd.conf
echo "interface=$interface" >> /etc/hostapd/hostapd.conf
echo "ssid=$ssid" >> /etc/hostapd/hostapd.conf
echo "hw_mode=g" >> /etc/hostapd/hostapd.conf
echo "channel=8" >> /etc/hostapd/hostapd.conf
echo "wmm_enabled=0" >> /etc/hostapd/hostapd.conf
echo "macaddr_acl=0" >> /etc/hostapd/hostapd.conf
echo "auth_algs=1" >> /etc/hostapd/hostapd.conf
echo "ignore_broadcast_ssid=0" >> /etc/hostapd/hostapd.conf
echo "wpa_passphrase=$wifipasswd" >> /etc/hostapd/hostapd.conf
echo "wpa_key_mgmt=WPA-PSK" >> /etc/hostapd/hostapd.conf
echo "wpa_pairwise=CCMP TKIP" >> /etc/hostapd/hostapd.conf
echo "rsn_pairwise=CCMP" >> /etc/hostapd/hostapd.conf
echo "#80211n - Change GB to your WiFi country code" >> /etc/hostapd/hostapd.conf
echo "country_code=IT" >> /etc/hostapd/hostapd.conf
echo "ieee80211n=1" >> /etc/hostapd/hostapd.conf
echo "ieee80211d=1" >> /etc/hostapd/hostapd.conf

sed -i s'/#DAEMON_CONF=""/DAEMON_CONF="\/etc\/hostapd\/hostapd.conf"/' /etc/default/hostapd
sed -i s'/DAEMON_OPTS=""/#DAEMON_OPTS=""/' /etc/default/hostapd

#add needed info to dnsmasq.conf
echo "#Hotspot config" >/etc/dnsmasq.conf
echo "interface=wlan1" >> /etc/dnsmasq.conf
echo "bind-dynamic" >> /etc/dnsmasq.conf
echo "server=8.8.8.8" >> /etc/dnsmasq.conf
echo "domain-needed" >> /etc/dnsmasq.conf
echo "bogus-priv" >> /etc/dnsmasq.conf
echo "dhcp-range=192.168.7.2,192.168.7.30,255.255.255.0,24h" >> /etc/dnsmasq.conf

mv /etc/network/interfaces /etc/network/interfaces.org

echo "source-directory /etc/network/interfaces.d" >> /etc/network/interfaces

echo "nohook wpa_supplicant" >> /etc/dhcpcd.conf

#setup ip forward
sed 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/' /etc/sysctl.conf

systemctl unmask dnsmasq.service
systemctl unmask hostapd.service
systemctl enable dnsmasq.service
systemctl enable hostapd.service 

echo;echo;echo
echo "A reboot is required to complete the setup"
